language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
  secure: yGnC7NMj6ugipCl8oa8rrPOfMwKQyEX7fYHDzUXKIAnJXkB35XP+Rw/g/tw6eYNM5dpjzbNbXLUlBNxEPN0qCM1uCU2e4xRzHVNOJJnY2TNYY+niXjGo7Phz5jCpnBMbA5lkH4yTA+UFysNMI46omK4BM2jd2+p4UJqoLaccDQo0kJ4oiTcUPjbiyIvtDjw2oxTvegFVL2AtwE4F87h0iXgytvRoqLZAMLXw+NRBTWSry8JXJhCFTFzEJp8Kd2J5eCv43F7/+9TRLCxVIys/F5LmjK4FZ6O8IlNiyWShezL3C7BWwrCAX6UtzkZh3TQeTjHVRXuIfErUHx8YD2MFog0+evVBsauGkmJ7oqIx6LFFauwQSy6rMerliR4Z7DYPjxhGkdcBm/OEUxys4q00sFNBsYeQFy70N6KCFsHtk9KRJ4GGPqEpAxLA6uWFgTKexl/blXC/itOJ96Zi3FBTvrgX2/tFiYWHOzQQa3IUZPFh3XIO6DD9+fWMGIitCUaIP0Xi7Oa17hljalrdMmFdm9NsdDd/o0I9nhKSI0ooEckTJiQY63U5ywYE6ZYbhJZWp9XH51M6Wi33pZ5xyy1JVTpYkyLFQk1B5vS2sqVhgUBGnCEDAhCTZakvgpwtjtAqZUW+/doZ+y2AlRBBJlpnfu+iQ/LltUdgbZkDGsJ5eNU=
  app: denverbnb
  skip_cleanup: true